### ISSUE TITLE
AWS.SharedIniFileCredentials needs refresh() called

### ISSUE THREAD

**Issue by cherrydev** [timdp/http-aws4#3]
If you don't call `refresh()` on AWS.SharedIniFileCredentials it will work for a simple profile but not for a role-assuming profile. I've tested that it works correctly if you call refresh() before using the credentials. I'll make a PR for you.

**Comment by timdp** [comment]
Really? That sucks since `getCredentials()` already takes a callback. Thanks for the upcoming PR!

**Comment by cherrydev** [comment]
It sucks and it's not going to be gorgeous, sorry! Feel free to unravel the nested lambdas. 
PR: https://github.com/timdp/http-aws4/pull/4
